# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100.0  # Hz

    arms_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arms_controller:
  ros__parameters:
    joints:
      - base_joint
      - joint1
      - joint2
      - joint3
      - gripper_extension
      - link4_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: true
gripper_controller:
  ros__parameters:
    joints:
      - left_gripper_joint
      - right_gripper_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: true